name: docker-telegram-bot

on:
  push:
    branches:
      - 'master'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - uses: actions/checkout@v2
      - 
        name: Copy Resource File
        run: cp ./xi.json telegram/
      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          context: ./telegram
          tags: neverbehave/xixi-haha-bot:latest